const { goto } = require('taiko');
const {getScreenshot} = require("../utils");
'use strict';
const {
    link, click,below,image,above,toRightOf,toLeftOf,button,rightClick,setViewPort
} = require('taiko');

step('Visit Playwright Documentation <url>', async url => {
    await setViewPort({width:1440, height:900})
    await goto(url)
    await click('Getting started');
    await click('Inspector');
    await click('Trace Viewer');
    await click('Test Generator');
    await click('Debugging tools');
    await click('Release notes');
    await click('Annotations');
    await click('API testing');
    await click('Authentication');
    await click('Command line');
    await click('Configuration');
    await click('Page Object Model');
    await click('Parallelism and sharding');
    await click('Parametrize tests');
    await click('Reporters');
    await click('Test retry');
    await click('Timeouts');
    await click('Visual comparisons');
    await click('Advanced: configuration');
    await click('Advanced: fixtures');
    await click('TypeScript');
    await click('Experimental: components');
    await click('Library');
    await click('Auto-waiting');
    await click('Authentication');
    await click('Browsers');
    await click('Browser Contexts');
    await click('Chrome Extensions');
    await click('Command line tools');
    await click('Dialogs');
    await click('Downloads');
    await click('Emulation');
    await click('Evaluating JavaScript');
    await click('Events');
    await click('Extensibility');
    await click('Frames');
    await click('Handles');
    await click('Input');
    await click('Locators');
    await click('Navigations');
    await click('Network');
    await click('Pages');
    await click('Page Object Models');
    await click('Screenshots');
    await click('Selectors');
    await click('Videos');
    await click('Migration');
    await click('Migrating from Protractor');
    await click('Integrations');
    await click('Docker');
    await click('Continuous Integration');
    await click('Third party runners');
    await click('Selenium Grid');
    await click('Supported languages');
    await goto('https://playwright.dev/docs/intro');
    await click('Getting started');
    await click('Inspector');
    await click('Trace Viewer');
    await click('Test Generator');
    await click('Debugging tools');
    await click('Release notes');
    await click('Annotations');
    await click('API testing');
    await click('Authentication');
    await click('Command line');
    await click('Configuration');
    await click('Page Object Model');
    await click('Parallelism and sharding');
    await click('Parametrize tests');
    await click('Reporters');
    await click('Test retry');
    await click('Timeouts');
    await click('Visual comparisons');
    await click('Advanced: configuration');
    await click('Advanced: fixtures');
    await click('TypeScript');
    await click('Experimental: components');
    await click('Library');
    await click('Auto-waiting');
    await click('Authentication');
    await click('Browsers');
    await click('Browser Contexts');
    await click('Chrome Extensions');
    await click('Command line tools');
    await click('Dialogs');
    await click('Downloads');
    await click('Emulation');
    await click('Evaluating JavaScript');
    await click('Events');
    await click('Extensibility');
    await click('Frames');
    await click('Handles');
    await click('Input');
    await click('Locators');
    await click('Navigations');
    await click('Network');
    await click('Pages');
    await click('Page Object Models');
    await click('Screenshots');
    await click('Selectors');
    await click('Videos');
    await click('Migration');
    await click('Migrating from Protractor');
    await click('Integrations');
    await click('Docker');
    await click('Continuous Integration');
    await click('Third party runners');
    await click('Selenium Grid');
    await click('Supported languages');
    await goto('https://playwright.dev/docs/intro');
    await click('Getting started');
    await click('Inspector');
    await click('Trace Viewer');
    await click('Test Generator');
    await click('Debugging tools');
    await click('Release notes');
    await click('Annotations');
    await click('API testing');
    await click('Authentication');
    await click('Command line');
    await click('Configuration');
    await click('Page Object Model');
    await click('Parallelism and sharding');
    await click('Parametrize tests');
    await click('Reporters');
    await click('Test retry');
    await click('Timeouts');
    await click('Visual comparisons');
    await click('Advanced: configuration');
    await click('Advanced: fixtures');
    await click('TypeScript');
    await click('Experimental: components');
    await click('Library');
    await click('Auto-waiting');
    await click('Authentication');
    await click('Browsers');
    await click('Browser Contexts');
    await click('Chrome Extensions');
    await click('Command line tools');
    await click('Dialogs');
    await click('Downloads');
    await click('Emulation');
    await click('Evaluating JavaScript');
    await click('Events');
    await click('Extensibility');
    await click('Frames');
    await click('Handles');
    await click('Input');
    await click('Locators');
    await click('Navigations');
    await click('Network');
    await click('Pages');
    await click('Page Object Models');
    await click('Screenshots');
    await click('Selectors');
    await click('Videos');
    await click('Migration');
    await click('Migrating from Protractor');
    await click('Integrations');
    await click('Docker');
    await click('Continuous Integration');
    await click('Third party runners');
    await click('Selenium Grid');
    await click('Supported languages');
    await goto('https://playwright.dev/docs/intro');
    await click('Getting started');
    await click('Inspector');
    await click('Trace Viewer');
    await click('Test Generator');
    await click('Debugging tools');
    await click('Release notes');
    await click('Annotations');
    await click('API testing');
    await click('Authentication');
    await click('Command line');
    await click('Configuration');
    await click('Page Object Model');
    await click('Parallelism and sharding');
    await click('Parametrize tests');
    await click('Reporters');
    await click('Test retry');
    await click('Timeouts');
    await click('Visual comparisons');
    await click('Advanced: configuration');
    await click('Advanced: fixtures');
    await click('TypeScript');
    await click('Experimental: components');
    await click('Library');
    await click('Auto-waiting');
    await click('Authentication');
    await click('Browsers');
    await click('Browser Contexts');
    await click('Chrome Extensions');
    await click('Command line tools');
    await click('Dialogs');
    await click('Downloads');
    await click('Emulation');
    await click('Evaluating JavaScript');
    await click('Events');
    await click('Extensibility');
    await click('Frames');
    await click('Handles');
    await click('Input');
    await click('Locators');
    await click('Navigations');
    await click('Network');
    await click('Pages');
    await click('Page Object Models');
    await click('Screenshots');
    await click('Selectors');
    await click('Videos');
    await click('Migration');
    await click('Migrating from Protractor');
    await click('Integrations');
    await click('Docker');
    await click('Continuous Integration');
    await click('Third party runners');
    await click('Selenium Grid');
    await click('Supported languages');
    await goto('https://playwright.dev/docs/intro');
    await click('Getting started');
    await click('Inspector');
    await click('Trace Viewer');
    await click('Test Generator');
    await click('Debugging tools');
    await click('Release notes');
    await click('Annotations');
    await click('API testing');
    await click('Authentication');
    await click('Command line');
    await click('Configuration');
    await click('Page Object Model');
    await click('Parallelism and sharding');
    await click('Parametrize tests');
    await click('Reporters');
    await click('Test retry');
    await click('Timeouts');
    await click('Visual comparisons');
    await click('Advanced: configuration');
    await click('Advanced: fixtures');
    await click('TypeScript');
    await click('Experimental: components');
    await click('Library');
    await click('Auto-waiting');
    await click('Authentication');
    await click('Browsers');
    await click('Browser Contexts');
    await click('Chrome Extensions');
    await click('Command line tools');
    await click('Dialogs');
    await click('Downloads');
    await click('Emulation');
    await click('Evaluating JavaScript');
    await click('Events');
    await click('Extensibility');
    await click('Frames');
    await click('Handles');
    await click('Input');
    await click('Locators');
    await click('Navigations');
    await click('Network');
    await click('Pages');
    await click('Page Object Models');
    await click('Screenshots');
    await click('Selectors');
    await click('Videos');
    await click('Migration');
    await click('Migrating from Protractor');
    await click('Integrations');
    await click('Docker');
    await click('Continuous Integration');
    await click('Third party runners');
    await click('Selenium Grid');
    await click('Supported languages');
});


step('Visit Docker Documentation <url>', async url => {
  await setViewPort({width:1440, height:900})
  await goto(url)
  await click('Get started');
  await click('Overview');
  await click('Node.js');
  await click('Overview');
  await click('Run containers');
  await click('Develop your app');
  await click('Run your tests');
  await click('Configure CI/CD');
  await click('Deploy your app');
  await click('Python');
  await click('Run containers');
  await click('Develop your app');
  await click('Configure CI/CD');
  await click('Deploy your app');
  await click('Java');
  await click('Overview');
  await click('Run containers');
  await click('Develop your app');
  await click('Run your tests');
  await click('Configure CI/CD');
  await click('Deploy your app');
  await click('Go');
  await click('Overview');
  await click('Run containers');
  await click('Develop your app');
  await click('Run your tests');
  await click('Configure CI/CD');
  await click('Deploy your app');
  await click('Develop with Docker');
  await click('Overview');
  await click('Best practices');
  await click('Dockerfile best practices');
  await click('Build images with BuildKit');
  await click('Use multi-stage builds');
  await click('Manage images');
  await click('Create your own base image (advanced)');
  await click('Scan images');
  await click('Set up CI/CD');
  await click('CI/CD Best practices');
  await click('Configure GitHub Actions');
  await click('Deploy your app to the cloud');
  await click('Docker and ACI');
  await click('ACI container features');
  await click('ACI Compose features');
  await click('Docker and ECS');
  await click('Docker ECS integration architecture');
  await click('ECS Compose features');
  await click('ECS Compose examples');
  await click('Run your app in production');
  await click('Orchestration');
  await click('Overview');
  await click('Deploy to Kubernetes');
  await click('Deploy to Swarm');
  await click('Configure all objects');
  await click('Apply custom metadata to objects');
  await click('Prune unused objects');
  await click('Format command and log output');
  await click('Configure the daemon');
  await click('Configure and run Docker');
  await click('Control Docker with systemd');
  await click('Collect metrics with Prometheus');
  await click('Configure containers');
  await click('Start containers automatically');
  await click('Keep containers alive during daemon downtime');
  await click('Run multiple services in a container');
  await click('Container runtime metrics');
  await click('Runtime options with Memory, CPUs, and GPUs');
  await click('Logging');
  await click('Configure logging drivers');
  await click('Use docker logs with a logging driver');
  await click('Use a logging driver plugin');
  await click('Customize log driver output');
  await click('Logging driver details');
  await click('Local file logging driver');
  await click('Logentries logging driver');
  await click('JSON File logging driver');
  await click('Graylog Extended Format (GELF) logging driver');
  await click('Syslog logging driver');
  await click('Amazon CloudWatch logs logging driver');
  await click('ETW logging driver');
  await click('Fluentd logging driver');
  await click('Google Cloud logging driver');
  await click('Journald logging driver');
  await click('Splunk logging driver');
  await click('Scale your app');
  await click('Swarm mode overview');
  await click('Swarm mode key concepts');
  await click('Get started with swarm mode');
  await click('Set up for the tutorial');
  await click('Create a swarm');
  await click('Add nodes to the swarm');
  await click('Deploy a service');
  await click('Inspect the service');
  await click('Scale the service');
  await click('Delete the service');
  await click('Apply rolling updates');
  await click('Drain a node');
  await click('Use swarm mode routing mesh');
  await click('How swarm mode works');
  await click('How nodes work');
  await click('How services work');
  await click('Manage swarm security with PKI');
  await click('Swarm task states');
  await click('Run Docker in swarm mode');
  await click('Join nodes to a swarm');
  await click('Manage nodes in a swarm');
  await click('Deploy services to a swarm');
  await click('Store service configuration data');
  await click('Manage sensitive data with Docker secrets');
  await click('Lock your swarm');
  await click('Swarm administration guide');
  await click('Raft consensus in swarm mode');
  await click('Extend Docker');
  await click('Managed plugin system');
  await click('Access authorization plugin');
  await click('Extending Docker with plugins');
  await click('Docker network driver plugins');
  await click('Volume plugins');
  await click('Plugin configuration');
  await click('Plugins');
  await click('Configure networking');
  await click('Networking overview');
  await click('Use bridge networks');
  await click('Use overlay networks');
  await click('Use host networking');
  await click('Use IPvlan networks');
  await click('Use Macvlan networks');
  await click('Disable networking for a container');
  await click('Networking tutorials');
  await click('Bridge network tutorial');
  await click('Host networking tutorial');
  await click('Overlay networking tutorial');
  await click('Macvlan network tutorial');
  await click('Configure the daemon and containers');
  await click('Configure the daemon for IPv6');
  await click('Docker and iptables');
  await click('Container networking');
  await click('Configure Docker to use a proxy server');
  await click('Legacy networking content');
  await click('(Legacy) Container links');
  await click('Manage application data');
  await click('Storage overview');
  await click('Volumes');
  await click('Bind mounts');
  await click('tmpfs mounts');
  await click('Troubleshoot volume problems');
  await click('Store data within containers');
  await click('About storage drivers');
  await click('Select a storage driver');
  await click('Use the AUFS storage driver');
  await click('Use the Btrfs storage driver');
  await click('Use the Device mapper storage driver');
  await click('Use the OverlayFS storage driver');
  await click('Use the ZFS storage driver');
  await click('Use the VFS storage driver');
  await click('Educational resources');
  await click('Contribute to documentation');
});
