---
version: "0.1"
globalTimeout: 90
testSuiteTimeout: 90
testSuiteStep: 90
runson: linux
autosplit: true
retryOnFailure: false
maxRetries: 5
concurrency: 2
pre:
  - npm install
  - curl -SsL https://downloads.gauge.org/stable | sh
cacheKey: '{{ checksum "package-lock.json" }}'
cacheDirectories:
  - node_modules
testDiscovery:
  type: raw
  mode: dynamic
  command: grep -lr ' ' specs/*.spec
testRunnerCommand: gauge run $test
