---
version: "0.1"
globalTimeout: 90
testSuiteTimeout: 90
testSuiteStep: 90
runson: mac
autosplit: true
retryOnFailure: true
maxRetries: 5
concurrency: 3
pre:
  - npm install
  - npm install -g @getgauge/cli
cacheKey: '{{ checksum "package-lock.json" }}'
cacheDirectories:
  - node_modules
testDiscovery:
  type: raw
  mode: dynamic
  command: grep -lr ' ' specs/*.spec
testRunnerCommand: gauge run $test
