---
version: '0.1'
matrix:
  os: [win]
  files: ["specs/open_playwright_doc1.spec","specs/open_playwright_doc2.spec","specs/open_playwright_doc3.spec"]
runson: ${matrix.os}
pre:
  - npm install
cacheKey: '{{ checksum "package-lock.json" }}'
cacheDirectories:
  - node_modules
testSuites:
  - gauge run $files
